In [3]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
from IPython.display import Image 
from io import StringIO
import pydotplus
from sklearn import preprocessing
from sklearn import tree
%matplotlib inline

In [4]:
def convert_yes_no(txt):
    if 'yes' in txt:
        return 1
    else:
        return 0

In [5]:
def plot_decision_tree(clf,feature_name,target_name):
    dot_data = StringIO()  
    tree.export_graphviz(clf, out_file=dot_data,  
                         feature_names=feature_name,  
                         class_names=target_name,  
                         filled=True, rounded=True,  
                         special_characters=True)  
    graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
    return Image(graph.create_png())

In [6]:
df = pd.read_csv('tennis.csv')

In [7]:
df

     outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [8]:
df.windy = df.windy.astype(int)
df.play = df.play.apply(convert_yes_no)

In [9]:
df

     outlook  temp humidity  windy  play
0      sunny   hot     high      0     0
1      sunny   hot     high      1     0
2   overcast   hot     high      0     1
3      rainy  mild     high      0     1
4      rainy  cool   normal      0     1
5      rainy  cool   normal      1     0
6   overcast  cool   normal      1     1
7      sunny  mild     high      0     0
8      sunny  cool   normal      0     1
9      rainy  mild   normal      0     1
10     sunny  mild   normal      1     1
11  overcast  mild     high      1     1
12  overcast   hot   normal      0     1
13     rainy  mild     high      1     0

In [10]:
df = pd.get_dummies(df)
df

,windy,play,outlook_overcast,outlook_rainy,outlook_sunny,temp_cool,temp_hot,temp_mild,humidity_high,humidity_normal
0,0,0,0,0,1,0,1,0,1,0
1,1,0,0,0,1,0,1,0,1,0
2,0,1,1,0,0,0,1,0,1,0
3,0,1,0,1,0,0,0,1,1,0
4,0,1,0,1,0,1,0,0,0,1
5,1,0,0,1,0,1,0,0,0,1
6,1,1,1,0,0,1,0,0,0,1
7,0,0,0,0,1,0,0,1,1,0
8,0,1,0,0,1,1,0,0,0,1
9,0,1,0,1,0,0,0,1,0,1
10,1,1,0,0,1,0,0,1,0,1
11,1,1,1,0,0,0,0,1,1,0
12,0,1,1,0,0,0,1,0,0,1
13,1,0,0,1,0,0,0,1,1,0

In [11]:
X_train = df.loc[:, df.columns != 'play']

In [12]:
Y_train = df.play

In [13]:
clf = tree.DecisionTreeClassifier(criterion='entropy')

In [14]:
clf = clf.fit(X_train,Y_train)

In [17]:
plot_decision_tree(clf, X_train.columns,df.columns[1])

InvocationException: GraphViz's executables not found